### ISSUE TITLE
Font size of loaded mods displayed on main screen

### ISSUE THREAD

**Issue by kyalmiracle** [Climeron/PvZ-Fusion-Tools#1]
I have visual issues when playing in windowed mode and setting the resolution to low (800 x 480 pixels) on the main monitor. The font size is large and covers almost the entire screen. I have an idea to adjust the font size to fit the screen for better visuals.

![800 480](https://github.com/user-attachments/assets/274b058b-2896-4d08-a7f1-f03a573dd42c)

![1920  1080](https://github.com/user-attachments/assets/9fc4d72a-4680-4d31-96a6-b8104bc59fd8)

**Comment by Climeron** [comment]
Didn't expect anyone to play in a small window. Okay, I'll think about it.

**Comment by Climeron** [comment]
I tried to fix this problem in v214.0.1. If the problem is fixed, you can close the issue.

**Comment by kyalmiracle** [comment]
Awesome, I played in windowed mode, and it displayed perfectly!
