### ISSUE TITLE
При изменении сложности на легкую проподает динамический логотип

### ISSUE THREAD

**Issue by ilnarildarovuch** [Climeron/PvZ-Fusion-Tools#2]
![Снимок экрана 2024-12-02 211443](https://github.com/user-attachments/assets/babeaf01-f69d-4879-afa9-2ef1ab105bcf)
![Снимок экрана 2024-12-02 211447](https://github.com/user-attachments/assets/96f13bfa-6f3b-420a-9d46-ed5c9e8c3720)

**Comment by ilnarildarovuch** [comment]
Вроде как там (в оригинале) менялся от этого логотип на темный.

**Comment by Climeron** [comment]
Это нормально, так как при кликах по этому окну в местах, где есть кнопки из меню, триггерится их нажатие и поэтому скрывается текст. Особо не вижу смысла это как-то исправлять.

**Comment by Climeron** [comment]
Это версия 2.1.4? Почему тогда в лого пишется 2.1.3? Там же версия подцепляется автоматически прямо из игры.

**Comment by ilnarildarovuch** [comment]
Да, это 2.1.4, но как оказалось оно записалось в конфиг в строй версии, и поэтому так отображается
